### ISSUE TITLE
Power Query Editor 中数据解析错误

### ISSUE THREAD

**Issue by CharlesLiu7** [blaulan/beancount-pbi#1]
Power Query Editor中解析 `example.pbix` 时候出现以下错误
```
DataSource.Error: ADO.NET: Python script error.
<pi>KeyError: 'links'

The above exception was the direct cause of the following exception:

KeyError: 'links'
</pi>
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
<pi>KeyError: 'links'

The above exception was the direct cause of the following exception:

KeyError: 'links'
</pi>
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException
```

使用系统python运行 `get_records.py` 手动修改 `example.beancount` 为 `input_file` 是可以正确获得 records 的。请问下pbi这是哪里出现问题了呀？

系统： win10
python版本：3.7.9
pbi Version: 2.112.1161.0 64-bit (2022年12月)

**Comment by CharlesLiu7** [comment]
Tips: beancount 的主文件最好输入绝对路径，例如 `C:/Users/user/Downloads/beancount-pbi/main.bean` ，此时我解析成功。

**Comment by blaulan** [comment]
> Tips: beancount 的主文件最好输入绝对路径，例如 `C:/Users/user/Downloads/beancount-pbi/main.bean` ，此时我解析成功。

对的，Power BI 里的 python 只支持绝对路径读取。
